/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sap.escooters.launcher;


import sap.escooters.data_source_layer.DataSourceLayer;
import sap.escooters.data_source_layer.DataSourceLayerImpl;
import sap.escooters.domain_layer.DomainLayer;
import sap.escooters.domain_layer.DomainLayerImpl;
import sap.escooters.presentation_layer.PresentationLayer;
import sap.escooters.presentation_layer.PresentationLayerImpl;
import sap.escooters.service_layer.ServiceLayer;
import sap.escooters.service_layer.ServiceLayerImpl;

import java.util.Optional;

public class EScooterManagementSystem {
    public static void main(String[] args) {
        DataSourceLayer dataSourceLayer = new DataSourceLayerImpl("dbase");
        DomainLayer domainLayer = new DomainLayerImpl();
        ServiceLayer serviceLayer = new ServiceLayerImpl();
        PresentationLayer presentationLayer = new PresentationLayerImpl(8081);

        dataSourceLayer.init(Optional.empty());
        domainLayer.init(Optional.of(dataSourceLayer));
        serviceLayer.init(Optional.of(domainLayer));
        presentationLayer.init(Optional.of(serviceLayer));
    }
}
