/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package users_service

import io.vertx.core.Vertx

fun main() {
    val vertx = Vertx.vertx()
    vertx.deployVerticle(UsersServiceVerticle())
}