/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package api_gateway

import kotlin.test.Test

class ApiGatewayTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = ApiGateway()
    }
}
